/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  // Vue
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const inject: typeof import('vue')['inject']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onMounted: typeof import('vue')['onMounted']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const ref: typeof import('vue')['ref']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowRef: typeof import('vue')['shallowRef']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const unref: typeof import('vue')['unref']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  
  // Vue Router
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  
  // Pinia
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const defineStore: typeof import('pinia')['defineStore']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  
  // VueUse
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useLocalStorage: typeof import('@vueuse/core')['useLocalStorage']
  const useSessionStorage: typeof import('@vueuse/core')['useSessionStorage']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useToggle: typeof import('@vueuse/core')['useToggle']
  
  // Ant Design Vue
  const message: typeof import('ant-design-vue/es')['message']
  const notification: typeof import('ant-design-vue/es')['notification']
  const Modal: typeof import('ant-design-vue/es')['Modal']
  
  // Utils
  const dayjs: typeof import('dayjs')['default']
  const axios: typeof import('axios')['default']
}